controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.263
    wheel_radius: 0.0325

    # pose_covariance_diagonal: [0.05, 0.05, 0.0, 0.0, 0.0, 0.01]
    # twist_covariance_diagonal: [0.05, 0.05, 0.0, 0.0, 0.0, 0.01] 

    # pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    # twist_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01] 

    # pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.01]
    # twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.01] 

    # pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0] 

    use_stamped_vel: false

imu_broadcaster:
  ros__parameters:

    sensor_name: mpu6050
    frame_id: imu_link

    # static_covariance_orientation: [0.005, 0.0, 0.0, 0.0, 0.005, 0.0, 0.0, 0.0, 0.005] # Imu orientation not fused so this might not matter
    # static_covariance_angular_velocity: [5.76e-04, 0.0, 0.0, 0.0, 5.76e-04, 0.0, 0.0, 0.0, 5.76e-04]
    # static_covariance_linear_acceleration: [9.8067e-03, 0.0, 0.0, 0.0, 9.8067e-03, 0.0, 0.0, 0.0, 9.8067e-03]

    # static_covariance_orientation: [0.005, 0.0, 0.0, 0.005, 0.0, 0.0, 0.005, 0.0, 0.0] # Imu orientation not fused so this might not matter
    # static_covariance_angular_velocity: [5.76e-04, 0.0, 0.0, 5.76e-04, 0.0, 0.0, 5.76e-04, 0.0, 0.0]
    # # static_covariance_linear_acceleration: [9.8067e-03, 0.0, 0.0, 9.8067e-03, 0.0, 0.0, 0.0, 0.0, 0.0]
    # static_covariance_linear_acceleration: [9.8067e-03, 0.0, 0.0, 9.8067e-03, 0.0, 0.0, 9.8067e-03, 0.0, 0.0]

    # open_loop: false

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN
# joint_broad:
#   ros__parameters:
